-
  ros1_package_name: 'msg_set'
  ros1_message_name: 'ObjectBox'
  ros2_package_name: 'msg_set_msgs'
  ros2_message_name: 'ObjectInfo'
  fields_1_to_2:
    x1: 'x1'
    y1: 'y1'
    x2: 'x2'
    y2: 'y2'
    label: 'label'
    id: 'id'

-
  ros1_package_name: 'msg_set'
  ros1_message_name: 'ObjectDetection'
  ros2_package_name: 'msg_set_msgs'
  ros2_message_name: 'ObjectDetection'
  fields_1_to_2:
    header: 'header'
    flag: 'flag'
    roll: 'roll'
    pitch: 'pitch'
    yaw: 'yaw'
    BoxesInfo: 'info'
