#####################################################
##命名规则                                     
##topic带坐标系： 包名/坐标系(global/world/local)/消息命名
##topic不带坐标系： 包名/消息命名
##topic中若不带drone_id： /包名/消息命名
#####################################################
Version: V2.0.0
drone_name: drone_999 #暂时不用

# ----------------公用消息-------------------
#黄晓巍
uav_state_machine:
  usm_state_topic: uav_state_machine/usm_state                  #状态机发布当前状态 [std_msgs::msg::Int32]                 
  usm_info_topic: uav_state_machine/data_info                   #状态机发布相关信息/状态/解锁点 [msg_set_msgs::msg::UsmDataInfo]
  ctrl_state_topic: uav_state_machine/ctrl_state                #状态机接收切换状态 [msg_set_msgs::msg::UsmCtrlState]                
  ctrl_arm_topic: uav_state_machine/armed_signal                #状态机接收解锁/断桨 [std_msgs::msg::Int32]  
  algo_cmd_topic: uav_state_machine/local/algo_cmd              #状态机接收的setpoint [msg_set_msgs::msg::UsmAlgoCmd]
  takeoff_height_topic: uav_state_machine/local/takeoff_height  #状态机接收takeoff高度 [std_msgs::msg::Float32]

#吴天皓
global_to_local:
  world_odom_topic: global2local/world/odom                     #发布world系odom [nav_msgs::msg::Odometry]
  world_pose_topic: global2local/world/pose                     #发布world系pose [geometry_msgs::msg::PoseStamped]
  world_multitask_topic: global2local/world/multitask           #发布world系任务流 [msg_set_msgs::msg::MultiTask]
  world_jump_task_topic: global2local/world/jump_task           #发布world系任务流跳转 [msg_set_msgs::msg::JumpTask]
  world_return_task_topic: global2local/world/return_task       #发布world系返航任务 [msg_set_msgs::msg::MultiTask]
  world_cover_task_topic: global2local/world/cover_task         #发布world系伴随任务 [msg_set_msgs::msg::CoverTask]
  world_cover_path_topic: global2local/world/cover_path         #发布world系伴随任务路径点 [mavros_msgs::msg::WaypointList]
  world_algo_cmd_topic: global2local/world/algo_cmd             #接收world系setpoint [msg_set_msgs::msg::UsmAlgoCmd]
  world_cover_goalpoint_topic: global2local/world/cover_goalpoint     #接收std_msgs::msg::Float32MultiArray ，三位，分别是x_lat,y_lon,z_alt
  target_pose_topic: global2local/global/target_pose            #发布全局目标点 [msg_set_msgs::msg::TargetsGps]

#徐鹏、汤佳境
sensor:
  depth_topic: feynman_camera/depth0/image_raw  
  uwb_topic: nlink_linktrack_nodeframe2

#豆扬名
perception:
  image_select_topic: perception/input/image_select   #rgb or ir   [std_msgs::msg::Int32] 0:rgb 1:ir
  rgb_image_topic: perception/private/rgb_img         #rgb 可见光图像 [sensor_msgs::msg::Image]
  ir_image_topic: perception/private/ir_img           #ir 红外图像    [sensor_msgs::msg::Image]
  stream_flag_topic: perception/input/rtsp_flag       #拉流信号       [std_msgs::msg::Float32] 1 拉流
  ptz_status_topic:  percepiton/output/ptz_status     #云台状态       [std_msgs::msg::Float32MultiArray] roll, pitch, yaw
  perception_task_method_topic: perception/input/task_method #任务   [std_msgs::msg::Int32]
  upd_det_info_topic: perception/output/det_data      #输出字节流     [std_msgs::msg::UInt8MultiArray]
  track_det_info_topic: perception/output/track_info  #目标跟踪结果 [std_msgs::msg::Float32MultiArray] 1. 无目标 发送{0.0f} 2. 有目标 发送{flag, x, y, z, x1, y1, x2, y2, roll, pitch, yaw} flag:-1静止目标 1动态目标 x,y,z距离 x1,y1,x2,y2 box坐标 roll,pitch,yaw云台状态
  ptz_flag_topic: perception/output/ptz_flag          #云台信号     [std_msgs::msg::Int32] 1:正常 0：异常
  camera_info: perception/output/camera_info
  object_detection_topic: perception/output/object_detection
  label_filter_topic: perception/input/label_filter
  track_ctrl_topic: perception/input/track_ctrl
  ptz_ctrl_topic: perception/input/ptz_ctrl
  perception_info_topic: perception/output/perception_info 
  track_img_topic: perception/output/track_jpg_img
  snap_jpg_topic: perception/input/snap_jpg
  video_record_ctrl_topic: perception/input/video_record/ctrl_flag #视频录制指令 [std_msgs::msg::Int8]  1:打开  -1：关闭
  video_record_state_topic: perception/output/video_record/state #无人机当前录制状态 [std_msgs::msg::Int8] 1:打开  -1：关闭
  weather_state: task_manage/weather_state # 变量类型 int32_t 0:白天 1：夜间


#汤佳境
swarm_bridge: 

#黄栩
light:
  light_ctrl_topic: light/input/ctrl_flag #int8  1:打开  -1：关闭
  light_state_topic: light/output/state #int8  1:打开  -1：关闭
  



# ----------------特定消息-------------------
#李博
backend:
  multitask: swarms_backend/global/multitask                 #任务流发布 [msg_set_msgs::msg::MultiTask]
  jump_task: swarms_backend/global/jump_task                 #任务流跳转 [msg_set_msgs::msg::JumpTask]
  return_task: swarms_backend/global/return_task             #返航任务 [msg_set_msgs::msg::MultiTask]
  pause_task: swarms_backend/pause_task                      #任务暂停/恢复 [std_msgs::msg::Bool]
  cover_task: swarms_backend/global/cover_task               #伴随任务发布 [msg_set_msgs::msg::CoverTask]
  cover_path: swarms_backend/global/cover_path               #调整伴随任务路径点 [mavros_msgs::msg::WaypointList]
  cover_param: swarms_backend/cover_param                    #伴随任务参数发布 [msg_set_msgs::msg::CoverParam]
  cover_goalpoint: swarms_backend/global/cover_goalpoint     #伴随任务目标点 [std_msgs::msg::Float32MultiArray, 三位，分别是x_lat,y_lon,z_alt]
  global_param: swarms_backend/global_param                  #预设的一些情况处理方法 [msg_set_msgs::msg::GlobalParam]
  cancel_task: swarms_backend/cancel_task                    #取消任务 [std_msgs::msg::Bool]
  drones_adjust: swarms_backend/drones_adjust                #无人机组的编号 [msg_set_msgs::msg::AdjustTasks]
  ctl_state_dispatch: swarms_backend/ctl_state_dispatch      #单机控制发布(2:起飞、3:悬停、4:降落、12:取消跟踪、14:at、28:定点dj、1000:解锁、1001:上锁) [std_msgs::msg::Int32]
  relay_height: swarms_backend/relay_height                  #中继无人机高度 [std_msgs::msg::Float32]
  image_get: swarms_backend/image_get                        #无人机保存图像 [std_msgs::msg::UInt8]
  ptz_control: swarms_backend/ptz_control                    #无人机云台控制 [std_msgs::msg::Int32MultiArray]
  throw: swarms_backend/throw                                #抛投 [std_msgs::msg::Bool] true
  pose_record: swarms_backend/pose_record                    #无人船位置数据保存 [std_msgs::msg::Bool] true true：代表开始，false：代表结束

task:
#刘梦杰
  task_manage:
    task_info_topic: tasks/info  # int16,成功1，失败0，其余情况后续添加
    fence_out_topic: task_manage/fence_out  #fence
    task_index_topic: task_manage/task_index  #
    all_info_topic_pub: /swarm_bridge/all_info
    mTask_confirm: task_manage/mTask_confirm # multitask 确认信息
    all_info_topic_sub: /swarm_bridge/group/all_info   # 原 all_poses
    takeoffgather_topic: task_manage/takeoff_gathering
    exploration_topic: task_manage/exploration
    search_topic: task_manage/search_attack
    attack_topic: task_manage/search_attack
    fixedpoint_topic: task_manage/fixed_point
    antijam_topic: task_manage/anti_jam
    dropreturn_topic: task_manage/drop_return
    shield_topic: task_manage/cover_task
    shield_path_topic: task_manage/cover_path
    shield_param_topic : task_manage/cover_param
    shield_jump_topic: task_manage/jump_index
    avoid_list_topic: algo_avoid/input
    cover_reach_index: task_shield/past_index
    confirm_info: task_manage/confirm_info # cover_task 确认信息
    cover_confirm: task_manage/cover_confirm # cover_task 确认信息
    coverParam_confirm: task_manage/coverParam_con # cover_param 确认信息
    cover_jump_point: task_manage/jump_point  #jump 跳转某一个点
    drones_id_adjust: task_manage/drones_id 
    relay_topic: task_manage/relay_task  # [msg_set_msgs::msg::RelayTask]
    templates_state: task_manage/templates_state # 任务模板状态world_cover_task_topic: global2local/world/cover_taskse # 任务模板状态响应
    templates_state_response: task_manage/templates_state_response # 任务模板状态响应
    can_confirmed_flag: task_attack/can_confirmed_flag # attack 可否确认信号 [std_msgs::msg::Bool]
    attack_piture: task_attack/attack_piture ## attack 拉取一张图片 [std_msgs::msg::Bool]
    cruise_topic: task_manage/cruise # cruise 巡航任务话题 task_type 11 set_template_id(11)
    light_state: task_manage/light_state # light    true 开灯， false 关灯
    weather_state: task_manage/weather_state # 变量类型 int32_t 0:白天 1：夜间

#陈博文
  task_takeoffgather:
    take_one_sub_topic: /swarm_brige/group/take_one
    take_one_pub_topic: /swarm_brige/take_one
#汪桉旭
  task_search:
#吴天皓
  task_attack:
     target_info_topic: task_attack/targets_pose  # 目标信息 [msg_set_msgs::msg::TargetInfo]
#童清
  task_dropreturn:
#汪桉旭
  task_shield:
#
  task_fixedpoint: 
    operation_confirm: task_fixedpoint/operation_confirm # 定点dj确认信号 [std_msgs::msg::Bool]
    


algo:
  MOVE_POSITION:
    input_topic: move_position/input                          #接收多目标点消息 [msg_set_msgs::msg::MultiGoal]
    output_topic: move_position/output                        
  ET_TRACK:
    input_topic:  et_track/input
    output_topic: et_track/output                             # 与目标的相对位置以及距离 [msg_set_msgs::msg::EtOutput]
  SWARM_FORMATION:
    input_topic: swarm_formation/input
    output_topic: swarm_formation/output 
    swarm_traj_topic_pub: /swarm_bridge/broadcast_traj
    swarm_traj_topic_sub: /swarm_bridge/group/broadcast_traj
  ATTACK_GOAL:
    input_topic: algo_attack/input
    output_topic: algo_attack/output
  BUTTER_FLY:
    input_topic: butter_fly/input
    output_topic: butter_fly/output
  SEARCH:
    input_topic: algo_search/input
    output_topic: algo_search/output
  SWARM_EXPLORATION:
    input_topic: swarm_exploration/input
    output_topic: swarm_exploration/output
  SINGLE_EXPLORATION:
    input_topic: 
    output_topic: 
  ALGO_DROP:
    input_topic: algo_drop/input
    output_topic: algo_drop/output
  AIR_DROP:
    input_topic: air_drop/input
    output_topic: air_drop/output
  ALGO_RETURN:
    input_topic: algo_return/input
    output_topic: algo_return/output
  ALGO_CRUISE:
    input_topic: algo_cruise/input
    output_topic: algo_cruise/output
  GATHER:
    input_topic: algo_gather/input
    output_topic: algo_gather/output
  ET_SEARCH:
    input_topic: 
    output_topic: 
  ALGO_AVOID:
    input_topic: algo_avoid/input
    output_topic: algo_avoid/output 
  ALGO_TRACK:
    input_topic: algo_track/input
    output_topic: algo_track/output 
  ALGO_RISEMOVE:
    input_topic: algo_risemove/input
    output_topic: algo_risemove/output
  ALGO_RELAY:
    input_topic: algo_relay/input
    output_topic: algo_relay/output
  ALGO_POINT:
    input_topic: algo_point/input
    output_topic: algo_point/output
  ALGO_POINT_ATTACK:
    input_topic: algo_point_attack/input                                                  # [msg_set_msgs::msg::MultiGoalPoint]
    output_topic: algo_point_attack/output
  FORMATION_CONTROL:
    input_topic: formation_control/input
    output_topic: formation_control/output
  ALGO_TRANSFORMATION:
    input_topic: algo_transformation/input
    output_topic: algo_transformation/output

module:
  SINGLE_AVOIDANCE:
    input_topic: module_enroute/input
    output_topic: module_enroute/output 
  MOVE_POSITION_MODULE:
    input_topic: module_enroute/input                          #接收多目标点消息 [msg_set_msgs::msg::SaInput]
    output_topic: module_enroute/output                        #发布setpoint   [msg_set_msgs::msg::SaOutput]
  SWARM_ZDB:
    input_topic: swarm_zdb/input    #zdb 控制指令 [std_msgs::msg::Int8]
    output_topic: swarm_zdb/output  #zdb 状态信息 [std_msgs::msg::Int16]

