AlgoID:
  MOVE_POSITION       : 11
  ET_TRACK            : 12
  SWARM_FORMATION     : 13
  ATTACK_GOAL         : 14
  BUTTER_FLY          : 15
  SEARCH              : 16
  SWARM_EXPLORATION   : 17
  SINGLE_EXPLORATION  : 18
  ALGO_DROP           : 19
  AIR_DROP            : 20
  ALGO_RETURN         : 21
  GATHER              : 22
  ET_SEARCH           : 23
  ALGO_AVOID          : 24
  ALGO_TRACK          : 25
  ALGO_RELAY          : 26
  ALGO_RISEMOVE       : 27
  ALGO_POINT_ATTACK   : 28
  ALGO_CRUISE         : 29
  NIGHT_MOVE          : 30
  TRANS_FORMATION     : 31
  FORMATION_CONTROL   : 32
  AGILITY_FLY         : 33
